version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  dbdata:
